package com.sword.smvcm.users.pojo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class TbMember implements Serializable {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_member.id
   * @mbg.generated
   */
  private Integer id;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_member.user_id
   * @mbg.generated
   */
  private Integer userId;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_member.union_id
   * @mbg.generated
   */
  private String unionId;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_member.open_id
   * @mbg.generated
   */
  private String openId;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_member.realname
   * @mbg.generated
   */
  private String realname;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_member.avatar
   * @mbg.generated
   */
  private String avatar;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_member.sex
   * @mbg.generated
   */
  private Boolean sex;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_member.birthday
   * @mbg.generated
   */
  private Date birthday;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_member.email
   * @mbg.generated
   */
  private String email;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_member.qq
   * @mbg.generated
   */
  private String qq;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_member.ww
   * @mbg.generated
   */
  private String ww;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_member.time
   * @mbg.generated
   */
  private Date time;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_member.qqopenid
   * @mbg.generated
   */
  private String qqopenid;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_member.points
   * @mbg.generated
   */
  private Integer points;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_member.available_predeposit
   * @mbg.generated
   */
  private BigDecimal availablePredeposit;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_member.freeze_predeposit
   * @mbg.generated
   */
  private BigDecimal freezePredeposit;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_member.inform_allow
   * @mbg.generated
   */
  private Boolean informAllow;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_member.is_buy
   * @mbg.generated
   */
  private Boolean isBuy;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_member.is_allowtalk
   * @mbg.generated
   */
  private Boolean isAllowtalk;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_member.is_vip
   * @mbg.generated
   */
  private Boolean isVip;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_member.area_d
   * @mbg.generated
   */
  private Integer areaD;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_member.city_id
   * @mbg.generated
   */
  private Integer cityId;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_member.province_id
   * @mbg.generated
   */
  private Integer provinceId;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_member.areainfo
   * @mbg.generated
   */
  private String areainfo;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_member.privacy
   * @mbg.generated
   */
  private String privacy;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_member.access_token
   * @mbg.generated
   */
  private String accessToken;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_member.expires_in
   * @mbg.generated
   */
  private Integer expiresIn;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_member.refresh_token
   * @mbg.generated
   */
  private String refreshToken;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_member.scope
   * @mbg.generated
   */
  private String scope;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_member.qqinfo
   * @mbg.generated
   */
  private String qqinfo;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table tb_user_member
   * @mbg.generated
   */
  private static final long serialVersionUID = 1L;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_member.id
   * @return  the value of tb_user_member.id
   * @mbg.generated
   */
  public Integer getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_member.id
   * @param id  the value for tb_user_member.id
   * @mbg.generated
   */
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_member.user_id
   * @return  the value of tb_user_member.user_id
   * @mbg.generated
   */
  public Integer getUserId() {
    return userId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_member.user_id
   * @param userId  the value for tb_user_member.user_id
   * @mbg.generated
   */
  public void setUserId(Integer userId) {
    this.userId = userId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_member.union_id
   * @return  the value of tb_user_member.union_id
   * @mbg.generated
   */
  public String getUnionId() {
    return unionId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_member.union_id
   * @param unionId  the value for tb_user_member.union_id
   * @mbg.generated
   */
  public void setUnionId(String unionId) {
    this.unionId = unionId == null ? null : unionId.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_member.open_id
   * @return  the value of tb_user_member.open_id
   * @mbg.generated
   */
  public String getOpenId() {
    return openId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_member.open_id
   * @param openId  the value for tb_user_member.open_id
   * @mbg.generated
   */
  public void setOpenId(String openId) {
    this.openId = openId == null ? null : openId.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_member.realname
   * @return  the value of tb_user_member.realname
   * @mbg.generated
   */
  public String getRealname() {
    return realname;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_member.realname
   * @param realname  the value for tb_user_member.realname
   * @mbg.generated
   */
  public void setRealname(String realname) {
    this.realname = realname == null ? null : realname.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_member.avatar
   * @return  the value of tb_user_member.avatar
   * @mbg.generated
   */
  public String getAvatar() {
    return avatar;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_member.avatar
   * @param avatar  the value for tb_user_member.avatar
   * @mbg.generated
   */
  public void setAvatar(String avatar) {
    this.avatar = avatar == null ? null : avatar.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_member.sex
   * @return  the value of tb_user_member.sex
   * @mbg.generated
   */
  public Boolean getSex() {
    return sex;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_member.sex
   * @param sex  the value for tb_user_member.sex
   * @mbg.generated
   */
  public void setSex(Boolean sex) {
    this.sex = sex;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_member.birthday
   * @return  the value of tb_user_member.birthday
   * @mbg.generated
   */
  public Date getBirthday() {
    return birthday;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_member.birthday
   * @param birthday  the value for tb_user_member.birthday
   * @mbg.generated
   */
  public void setBirthday(Date birthday) {
    this.birthday = birthday;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_member.email
   * @return  the value of tb_user_member.email
   * @mbg.generated
   */
  public String getEmail() {
    return email;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_member.email
   * @param email  the value for tb_user_member.email
   * @mbg.generated
   */
  public void setEmail(String email) {
    this.email = email == null ? null : email.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_member.qq
   * @return  the value of tb_user_member.qq
   * @mbg.generated
   */
  public String getQq() {
    return qq;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_member.qq
   * @param qq  the value for tb_user_member.qq
   * @mbg.generated
   */
  public void setQq(String qq) {
    this.qq = qq == null ? null : qq.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_member.ww
   * @return  the value of tb_user_member.ww
   * @mbg.generated
   */
  public String getWw() {
    return ww;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_member.ww
   * @param ww  the value for tb_user_member.ww
   * @mbg.generated
   */
  public void setWw(String ww) {
    this.ww = ww == null ? null : ww.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_member.time
   * @return  the value of tb_user_member.time
   * @mbg.generated
   */
  public Date getTime() {
    return time;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_member.time
   * @param time  the value for tb_user_member.time
   * @mbg.generated
   */
  public void setTime(Date time) {
    this.time = time;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_member.qqopenid
   * @return  the value of tb_user_member.qqopenid
   * @mbg.generated
   */
  public String getQqopenid() {
    return qqopenid;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_member.qqopenid
   * @param qqopenid  the value for tb_user_member.qqopenid
   * @mbg.generated
   */
  public void setQqopenid(String qqopenid) {
    this.qqopenid = qqopenid == null ? null : qqopenid.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_member.points
   * @return  the value of tb_user_member.points
   * @mbg.generated
   */
  public Integer getPoints() {
    return points;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_member.points
   * @param points  the value for tb_user_member.points
   * @mbg.generated
   */
  public void setPoints(Integer points) {
    this.points = points;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_member.available_predeposit
   * @return  the value of tb_user_member.available_predeposit
   * @mbg.generated
   */
  public BigDecimal getAvailablePredeposit() {
    return availablePredeposit;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_member.available_predeposit
   * @param availablePredeposit  the value for tb_user_member.available_predeposit
   * @mbg.generated
   */
  public void setAvailablePredeposit(BigDecimal availablePredeposit) {
    this.availablePredeposit = availablePredeposit;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_member.freeze_predeposit
   * @return  the value of tb_user_member.freeze_predeposit
   * @mbg.generated
   */
  public BigDecimal getFreezePredeposit() {
    return freezePredeposit;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_member.freeze_predeposit
   * @param freezePredeposit  the value for tb_user_member.freeze_predeposit
   * @mbg.generated
   */
  public void setFreezePredeposit(BigDecimal freezePredeposit) {
    this.freezePredeposit = freezePredeposit;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_member.inform_allow
   * @return  the value of tb_user_member.inform_allow
   * @mbg.generated
   */
  public Boolean getInformAllow() {
    return informAllow;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_member.inform_allow
   * @param informAllow  the value for tb_user_member.inform_allow
   * @mbg.generated
   */
  public void setInformAllow(Boolean informAllow) {
    this.informAllow = informAllow;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_member.is_buy
   * @return  the value of tb_user_member.is_buy
   * @mbg.generated
   */
  public Boolean getIsBuy() {
    return isBuy;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_member.is_buy
   * @param isBuy  the value for tb_user_member.is_buy
   * @mbg.generated
   */
  public void setIsBuy(Boolean isBuy) {
    this.isBuy = isBuy;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_member.is_allowtalk
   * @return  the value of tb_user_member.is_allowtalk
   * @mbg.generated
   */
  public Boolean getIsAllowtalk() {
    return isAllowtalk;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_member.is_allowtalk
   * @param isAllowtalk  the value for tb_user_member.is_allowtalk
   * @mbg.generated
   */
  public void setIsAllowtalk(Boolean isAllowtalk) {
    this.isAllowtalk = isAllowtalk;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_member.is_vip
   * @return  the value of tb_user_member.is_vip
   * @mbg.generated
   */
  public Boolean getIsVip() {
    return isVip;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_member.is_vip
   * @param isVip  the value for tb_user_member.is_vip
   * @mbg.generated
   */
  public void setIsVip(Boolean isVip) {
    this.isVip = isVip;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_member.area_d
   * @return  the value of tb_user_member.area_d
   * @mbg.generated
   */
  public Integer getAreaD() {
    return areaD;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_member.area_d
   * @param areaD  the value for tb_user_member.area_d
   * @mbg.generated
   */
  public void setAreaD(Integer areaD) {
    this.areaD = areaD;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_member.city_id
   * @return  the value of tb_user_member.city_id
   * @mbg.generated
   */
  public Integer getCityId() {
    return cityId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_member.city_id
   * @param cityId  the value for tb_user_member.city_id
   * @mbg.generated
   */
  public void setCityId(Integer cityId) {
    this.cityId = cityId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_member.province_id
   * @return  the value of tb_user_member.province_id
   * @mbg.generated
   */
  public Integer getProvinceId() {
    return provinceId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_member.province_id
   * @param provinceId  the value for tb_user_member.province_id
   * @mbg.generated
   */
  public void setProvinceId(Integer provinceId) {
    this.provinceId = provinceId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_member.areainfo
   * @return  the value of tb_user_member.areainfo
   * @mbg.generated
   */
  public String getAreainfo() {
    return areainfo;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_member.areainfo
   * @param areainfo  the value for tb_user_member.areainfo
   * @mbg.generated
   */
  public void setAreainfo(String areainfo) {
    this.areainfo = areainfo == null ? null : areainfo.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_member.privacy
   * @return  the value of tb_user_member.privacy
   * @mbg.generated
   */
  public String getPrivacy() {
    return privacy;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_member.privacy
   * @param privacy  the value for tb_user_member.privacy
   * @mbg.generated
   */
  public void setPrivacy(String privacy) {
    this.privacy = privacy == null ? null : privacy.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_member.access_token
   * @return  the value of tb_user_member.access_token
   * @mbg.generated
   */
  public String getAccessToken() {
    return accessToken;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_member.access_token
   * @param accessToken  the value for tb_user_member.access_token
   * @mbg.generated
   */
  public void setAccessToken(String accessToken) {
    this.accessToken = accessToken == null ? null : accessToken.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_member.expires_in
   * @return  the value of tb_user_member.expires_in
   * @mbg.generated
   */
  public Integer getExpiresIn() {
    return expiresIn;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_member.expires_in
   * @param expiresIn  the value for tb_user_member.expires_in
   * @mbg.generated
   */
  public void setExpiresIn(Integer expiresIn) {
    this.expiresIn = expiresIn;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_member.refresh_token
   * @return  the value of tb_user_member.refresh_token
   * @mbg.generated
   */
  public String getRefreshToken() {
    return refreshToken;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_member.refresh_token
   * @param refreshToken  the value for tb_user_member.refresh_token
   * @mbg.generated
   */
  public void setRefreshToken(String refreshToken) {
    this.refreshToken = refreshToken == null ? null : refreshToken.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_member.scope
   * @return  the value of tb_user_member.scope
   * @mbg.generated
   */
  public String getScope() {
    return scope;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_member.scope
   * @param scope  the value for tb_user_member.scope
   * @mbg.generated
   */
  public void setScope(String scope) {
    this.scope = scope == null ? null : scope.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_member.qqinfo
   * @return  the value of tb_user_member.qqinfo
   * @mbg.generated
   */
  public String getQqinfo() {
    return qqinfo;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_member.qqinfo
   * @param qqinfo  the value for tb_user_member.qqinfo
   * @mbg.generated
   */
  public void setQqinfo(String qqinfo) {
    this.qqinfo = qqinfo == null ? null : qqinfo.trim();
  }
}