package com.sword.smvcm.users.pojo;

import java.io.Serializable;

public class TbRole implements Serializable {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_role.id
   * @mbg.generated
   */
  private Integer id;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_role.value
   * @mbg.generated
   */
  private String value;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_role.name
   * @mbg.generated
   */
  private String name;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_role.valid
   * @mbg.generated
   */
  private Integer valid;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table tb_role
   * @mbg.generated
   */
  private static final long serialVersionUID = 1L;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_role.id
   * @return  the value of tb_role.id
   * @mbg.generated
   */
  public Integer getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_role.id
   * @param id  the value for tb_role.id
   * @mbg.generated
   */
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_role.value
   * @return  the value of tb_role.value
   * @mbg.generated
   */
  public String getValue() {
    return value;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_role.value
   * @param value  the value for tb_role.value
   * @mbg.generated
   */
  public void setValue(String value) {
    this.value = value == null ? null : value.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_role.name
   * @return  the value of tb_role.name
   * @mbg.generated
   */
  public String getName() {
    return name;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_role.name
   * @param name  the value for tb_role.name
   * @mbg.generated
   */
  public void setName(String name) {
    this.name = name == null ? null : name.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_role.valid
   * @return  the value of tb_role.valid
   * @mbg.generated
   */
  public Integer getValid() {
    return valid;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_role.valid
   * @param valid  the value for tb_role.valid
   * @mbg.generated
   */
  public void setValid(Integer valid) {
    this.valid = valid;
  }
}