package com.sword.smvcm.users.pojo;

import java.io.Serializable;

public class TbUserRole implements Serializable {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_role.id
   * @mbg.generated
   */
  private Integer id;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_role.user_id
   * @mbg.generated
   */
  private Integer userId;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user_role.role_id
   * @mbg.generated
   */
  private Integer roleId;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table tb_user_role
   * @mbg.generated
   */
  private static final long serialVersionUID = 1L;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_role.id
   * @return  the value of tb_user_role.id
   * @mbg.generated
   */
  public Integer getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_role.id
   * @param id  the value for tb_user_role.id
   * @mbg.generated
   */
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_role.user_id
   * @return  the value of tb_user_role.user_id
   * @mbg.generated
   */
  public Integer getUserId() {
    return userId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_role.user_id
   * @param userId  the value for tb_user_role.user_id
   * @mbg.generated
   */
  public void setUserId(Integer userId) {
    this.userId = userId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user_role.role_id
   * @return  the value of tb_user_role.role_id
   * @mbg.generated
   */
  public Integer getRoleId() {
    return roleId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user_role.role_id
   * @param roleId  the value for tb_user_role.role_id
   * @mbg.generated
   */
  public void setRoleId(Integer roleId) {
    this.roleId = roleId;
  }
}