package com.sword.smvcm.users.pojo;

import java.io.Serializable;
import java.util.Date;

public class TbUser implements Serializable {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.id
   * @mbg.generated
   */
  private Integer id;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.username
   * @mbg.generated
   */
  private String username;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.nickname
   * @mbg.generated
   */
  private String nickname;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.realname
   * @mbg.generated
   */
  private String realname;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.password
   * @mbg.generated
   */
  private String password;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.salt
   * @mbg.generated
   */
  private String salt;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.mobile
   * @mbg.generated
   */
  private String mobile;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.login_ip
   * @mbg.generated
   */
  private String loginIp;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.login_time
   * @mbg.generated
   */
  private Date loginTime;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.last_login_ip
   * @mbg.generated
   */
  private String lastLoginIp;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.last_login_time
   * @mbg.generated
   */
  private Date lastLoginTime;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.create_time
   * @mbg.generated
   */
  private Date createTime;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.update_time
   * @mbg.generated
   */
  private Date updateTime;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.login_count
   * @mbg.generated
   */
  private Long loginCount;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.type
   * @mbg.generated
   */
  private Integer type;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.valid
   * @mbg.generated
   */
  private Integer valid;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table tb_user
   * @mbg.generated
   */
  private static final long serialVersionUID = 1L;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.id
   * @return  the value of tb_user.id
   * @mbg.generated
   */
  public Integer getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.id
   * @param id  the value for tb_user.id
   * @mbg.generated
   */
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.username
   * @return  the value of tb_user.username
   * @mbg.generated
   */
  public String getUsername() {
    return username;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.username
   * @param username  the value for tb_user.username
   * @mbg.generated
   */
  public void setUsername(String username) {
    this.username = username == null ? null : username.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.nickname
   * @return  the value of tb_user.nickname
   * @mbg.generated
   */
  public String getNickname() {
    return nickname;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.nickname
   * @param nickname  the value for tb_user.nickname
   * @mbg.generated
   */
  public void setNickname(String nickname) {
    this.nickname = nickname == null ? null : nickname.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.realname
   * @return  the value of tb_user.realname
   * @mbg.generated
   */
  public String getRealname() {
    return realname;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.realname
   * @param realname  the value for tb_user.realname
   * @mbg.generated
   */
  public void setRealname(String realname) {
    this.realname = realname == null ? null : realname.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.password
   * @return  the value of tb_user.password
   * @mbg.generated
   */
  public String getPassword() {
    return password;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.password
   * @param password  the value for tb_user.password
   * @mbg.generated
   */
  public void setPassword(String password) {
    this.password = password == null ? null : password.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.salt
   * @return  the value of tb_user.salt
   * @mbg.generated
   */
  public String getSalt() {
    return salt;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.salt
   * @param salt  the value for tb_user.salt
   * @mbg.generated
   */
  public void setSalt(String salt) {
    this.salt = salt == null ? null : salt.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.mobile
   * @return  the value of tb_user.mobile
   * @mbg.generated
   */
  public String getMobile() {
    return mobile;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.mobile
   * @param mobile  the value for tb_user.mobile
   * @mbg.generated
   */
  public void setMobile(String mobile) {
    this.mobile = mobile == null ? null : mobile.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.login_ip
   * @return  the value of tb_user.login_ip
   * @mbg.generated
   */
  public String getLoginIp() {
    return loginIp;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.login_ip
   * @param loginIp  the value for tb_user.login_ip
   * @mbg.generated
   */
  public void setLoginIp(String loginIp) {
    this.loginIp = loginIp == null ? null : loginIp.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.login_time
   * @return  the value of tb_user.login_time
   * @mbg.generated
   */
  public Date getLoginTime() {
    return loginTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.login_time
   * @param loginTime  the value for tb_user.login_time
   * @mbg.generated
   */
  public void setLoginTime(Date loginTime) {
    this.loginTime = loginTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.last_login_ip
   * @return  the value of tb_user.last_login_ip
   * @mbg.generated
   */
  public String getLastLoginIp() {
    return lastLoginIp;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.last_login_ip
   * @param lastLoginIp  the value for tb_user.last_login_ip
   * @mbg.generated
   */
  public void setLastLoginIp(String lastLoginIp) {
    this.lastLoginIp = lastLoginIp == null ? null : lastLoginIp.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.last_login_time
   * @return  the value of tb_user.last_login_time
   * @mbg.generated
   */
  public Date getLastLoginTime() {
    return lastLoginTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.last_login_time
   * @param lastLoginTime  the value for tb_user.last_login_time
   * @mbg.generated
   */
  public void setLastLoginTime(Date lastLoginTime) {
    this.lastLoginTime = lastLoginTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.create_time
   * @return  the value of tb_user.create_time
   * @mbg.generated
   */
  public Date getCreateTime() {
    return createTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.create_time
   * @param createTime  the value for tb_user.create_time
   * @mbg.generated
   */
  public void setCreateTime(Date createTime) {
    this.createTime = createTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.update_time
   * @return  the value of tb_user.update_time
   * @mbg.generated
   */
  public Date getUpdateTime() {
    return updateTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.update_time
   * @param updateTime  the value for tb_user.update_time
   * @mbg.generated
   */
  public void setUpdateTime(Date updateTime) {
    this.updateTime = updateTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.login_count
   * @return  the value of tb_user.login_count
   * @mbg.generated
   */
  public Long getLoginCount() {
    return loginCount;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.login_count
   * @param loginCount  the value for tb_user.login_count
   * @mbg.generated
   */
  public void setLoginCount(Long loginCount) {
    this.loginCount = loginCount;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.type
   * @return  the value of tb_user.type
   * @mbg.generated
   */
  public Integer getType() {
    return type;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.type
   * @param type  the value for tb_user.type
   * @mbg.generated
   */
  public void setType(Integer type) {
    this.type = type;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.valid
   * @return  the value of tb_user.valid
   * @mbg.generated
   */
  public Integer getValid() {
    return valid;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.valid
   * @param valid  the value for tb_user.valid
   * @mbg.generated
   */
  public void setValid(Integer valid) {
    this.valid = valid;
  }
}