package com.sword.smvcm.wx.menu.mapper;

import java.util.List;

import com.sword.smvcm.wx.menu.pojo.TbMenu;
import com.sword.smvcm.wx.menu.pojo.TbMenuExample;
import org.apache.ibatis.annotations.Param;

public interface TbMenuMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_menu
   * @mbg.generated
   */
  int deleteByExample(TbMenuExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_menu
   * @mbg.generated
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_menu
   * @mbg.generated
   */
  int insert(TbMenu record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_menu
   * @mbg.generated
   */
  int insertSelective(TbMenu record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_menu
   * @mbg.generated
   */List<TbMenu> selectByExample(TbMenuExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_menu
   * @mbg.generated
   */
  TbMenu selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_menu
   * @mbg.generated
   */int updateByExampleSelective(@Param("record") TbMenu record,@Param("example") TbMenuExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_menu
   * @mbg.generated
   */int updateByExample(@Param("record") TbMenu record,@Param("example") TbMenuExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_menu
   * @mbg.generated
   */
  int updateByPrimaryKeySelective(TbMenu record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_menu
   * @mbg.generated
   */
  int updateByPrimaryKey(TbMenu record);
}