package com.sword.smvcm.config.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.sword.smvcm.config.pojo.TbConfig;
import com.sword.smvcm.config.pojo.TbConfigExample;

public interface TbConfigMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_config
   * @mbg.generated
   */
  int deleteByExample(TbConfigExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_config
   * @mbg.generated
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_config
   * @mbg.generated
   */
  int insert(TbConfig record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_config
   * @mbg.generated
   */
  int insertSelective(TbConfig record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_config
   * @mbg.generated
   */List<TbConfig> selectByExampleWithBLOBs(TbConfigExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_config
   * @mbg.generated
   */List<TbConfig> selectByExample(TbConfigExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_config
   * @mbg.generated
   */
  TbConfig selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_config
   * @mbg.generated
   */int updateByExampleSelective(@Param("record") TbConfig record,@Param("example") TbConfigExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_config
   * @mbg.generated
   */int updateByExampleWithBLOBs(@Param("record") TbConfig record,@Param("example") TbConfigExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_config
   * @mbg.generated
   */int updateByExample(@Param("record") TbConfig record,@Param("example") TbConfigExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_config
   * @mbg.generated
   */
  int updateByPrimaryKeySelective(TbConfig record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_config
   * @mbg.generated
   */
  int updateByPrimaryKeyWithBLOBs(TbConfig record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_config
   * @mbg.generated
   */
  int updateByPrimaryKey(TbConfig record);
}