package com.sword.smvcm.users.mapper;

import com.sword.smvcm.users.pojo.TbRolePermission;
import com.sword.smvcm.users.pojo.TbRolePermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbRolePermissionMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_role_permission
   * @mbg.generated
   */
  int deleteByExample(TbRolePermissionExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_role_permission
   * @mbg.generated
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_role_permission
   * @mbg.generated
   */
  int insert(TbRolePermission record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_role_permission
   * @mbg.generated
   */
  int insertSelective(TbRolePermission record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_role_permission
   * @mbg.generated
   */List<TbRolePermission> selectByExample(TbRolePermissionExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_role_permission
   * @mbg.generated
   */
  TbRolePermission selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_role_permission
   * @mbg.generated
   */int updateByExampleSelective(@Param("record") TbRolePermission record,@Param("example") TbRolePermissionExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_role_permission
   * @mbg.generated
   */int updateByExample(@Param("record") TbRolePermission record,@Param("example") TbRolePermissionExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_role_permission
   * @mbg.generated
   */
  int updateByPrimaryKeySelective(TbRolePermission record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_role_permission
   * @mbg.generated
   */
  int updateByPrimaryKey(TbRolePermission record);
}