package com.sword.smvcm.users.mapper;

import com.sword.smvcm.users.pojo.TbUserRole;
import com.sword.smvcm.users.pojo.TbUserRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbUserRoleMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user_role
   * @mbg.generated
   */
  int deleteByExample(TbUserRoleExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user_role
   * @mbg.generated
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user_role
   * @mbg.generated
   */
  int insert(TbUserRole record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user_role
   * @mbg.generated
   */
  int insertSelective(TbUserRole record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user_role
   * @mbg.generated
   */List<TbUserRole> selectByExample(TbUserRoleExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user_role
   * @mbg.generated
   */
  TbUserRole selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user_role
   * @mbg.generated
   */int updateByExampleSelective(@Param("record") TbUserRole record,@Param("example") TbUserRoleExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user_role
   * @mbg.generated
   */int updateByExample(@Param("record") TbUserRole record,@Param("example") TbUserRoleExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user_role
   * @mbg.generated
   */
  int updateByPrimaryKeySelective(TbUserRole record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user_role
   * @mbg.generated
   */
  int updateByPrimaryKey(TbUserRole record);
}