package com.sword.smvcm.pojo;

import java.io.Serializable;
import java.util.Date;

public class TbConfig implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_config.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_config.config_group
     *
     * @mbg.generated
     */
    private String configGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_config.config_key
     *
     * @mbg.generated
     */
    private String configKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_config.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_config.config_value
     *
     * @mbg.generated
     */
    private String configValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_config
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_config.id
     *
     * @return the value of tb_config.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_config.id
     *
     * @param id the value for tb_config.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_config.config_group
     *
     * @return the value of tb_config.config_group
     *
     * @mbg.generated
     */
    public String getConfigGroup() {
        return configGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_config.config_group
     *
     * @param configGroup the value for tb_config.config_group
     *
     * @mbg.generated
     */
    public void setConfigGroup(String configGroup) {
        this.configGroup = configGroup == null ? null : configGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_config.config_key
     *
     * @return the value of tb_config.config_key
     *
     * @mbg.generated
     */
    public String getConfigKey() {
        return configKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_config.config_key
     *
     * @param configKey the value for tb_config.config_key
     *
     * @mbg.generated
     */
    public void setConfigKey(String configKey) {
        this.configKey = configKey == null ? null : configKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_config.update_time
     *
     * @return the value of tb_config.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_config.update_time
     *
     * @param updateTime the value for tb_config.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_config.config_value
     *
     * @return the value of tb_config.config_value
     *
     * @mbg.generated
     */
    public String getConfigValue() {
        return configValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_config.config_value
     *
     * @param configValue the value for tb_config.config_value
     *
     * @mbg.generated
     */
    public void setConfigValue(String configValue) {
        this.configValue = configValue == null ? null : configValue.trim();
    }
}